name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: make gradlew executable
        run: chmod +x ./gradlew
      - name: add api key property
        run: echo "API_KEY=\"${{ secrets.DOLARITO_API_KEY }}\"" >> local.properties
      - name: build debug
        run: ./gradlew app:assembleDebug
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: generated-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
