name: Build Release App Bundle

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: make gradlew executable
        run: chmod +x ./gradlew
      - name: add api key property
        run: echo "API_KEY=\"${{ secrets.DOLARITO_API_KEY }}\"" >> local.properties
      - name: build prod
        run: ./gradlew app:bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: upload to github
        uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: app/build/outputs/